drop table users cascade;
drop table user_achievements cascade ;
drop table user_history cascade ;
drop table topics cascade ;
drop table problems cascade ;
drop table problems_topics cascade;
drop table solutions cascade ;
drop table submissions cascade ;
drop table tutorials cascade ;
drop table contests cascade ;
drop table contest_problems cascade ;
drop table contest_participants cascade ;
drop table announcements cascade ;
drop table contest_announcements cascade ;
drop table contest_feedback cascade ;
drop table user_history cascade ;
drop table problem_history cascade ;
drop table announcement_history cascade ;
drop table contest_history cascade ;